
epochs: 500
eval_every: 10
public_ground_truth: data/public_ground_truth.csv
upsample_loss_lambda: 1.0
momentum: 0.999

memory_bank:
  queue_size: 65000
  feature_size: 128

model:
  downsample_layers: [2, 2, 2]
  upsample_layers: [2, 2, 2]
  
data:
  train_dir: data/train/
  query_dir: data/query/
  ref_dir: data/reference/
  batch_size: 32
  transforms:
    std:
      resize:
        size: [256, 256]
      to_tensor:
    aug:
      resize:
        size: [256, 256]
      random_flip:
      rand_aug:
        n_aug: 4
      to_tensor:

optim:
  name: sgd
  lr: 1.0
  weight_decay: 1.e-06

scheduler:
  name: cosine
  warmup_epochs: 10

loss_fn:
  normalize: True
  temperature: 0.5
